apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # ArgoCD Application 리소스는 infrastructure/kustomization.yaml에서 관리
  # - argocd/postgresql.yaml
  # - argocd/postgres-exporter.yaml
  # - argocd/postgres-exporter-read-0.yaml
  # - argocd/postgres-exporter-read-1.yaml
  - vault/postgresql-password.yaml
