apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # PostgreSQL databases
  - postgresql/argocd/postgresql.yaml
  - postgresql/argocd/postgres-exporter.yaml
  - postgresql/argocd/postgres-exporter-read-0.yaml
  - postgresql/argocd/postgres-exporter-read-1.yaml
  - postgresql-dev/argocd/postgresql-dev.yaml

  # Object storage
  - minio/argocd/minio.yaml

  # Database management tools
  - pgweb/argocd/pgweb.yaml
