apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-console
  namespace: minio
  labels:
    app: minio-console
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio-console
  template:
    metadata:
      labels:
        app: minio-console
    spec:
      containers:
        - name: console
          image: ghcr.io/georgmangold/console:v1.9.1
          ports:
            - containerPort: 9090
              name: http
          env:
            - name: CONSOLE_MINIO_SERVER
              value: "http://minio.minio.svc.cluster.local:9000"
            - name: CONSOLE_PBKDF_PASSPHRASE
              valueFrom:
                secretKeyRef:
                  name: minio-console-secret
                  key: CONSOLE_PBKDF_PASSPHRASE
            - name: CONSOLE_PBKDF_SALT
              valueFrom:
                secretKeyRef:
                  name: minio-console-secret
                  key: CONSOLE_PBKDF_SALT
            # OIDC Configuration
            - name: CONSOLE_IDP_URL
              value: "https://auth0213.kro.kr/.well-known/openid-configuration"
            - name: CONSOLE_IDP_CLIENT_ID
              value: "minio"
            - name: CONSOLE_IDP_SECRET
              valueFrom:
                secretKeyRef:
                  name: minio-oidc-secret
                  key: MINIO_IDENTITY_OPENID_CLIENT_SECRET
            - name: CONSOLE_IDP_CALLBACK
              value: "https://minio.minio0213.kro.kr/oauth_callback"
            - name: CONSOLE_IDP_SCOPES
              value: "openid,profile,email"
            - name: CONSOLE_IDP_CALLBACK_DYNAMIC
              value: "on"
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
            limits:
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: minio-console
  namespace: minio
spec:
  selector:
    app: minio-console
  ports:
    - port: 9090
      targetPort: 9090
      name: http
